- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - dconf-cli
      - python3-psutil

# Note: For Arch, the requirement is met by a dependency of systemd, only necessary on Debian-based
- name: ansible setup | install acl package
  tags: ansible,ansible-setup,packages
  package:
    name: acl
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
